# Generated by Django 4.1.1 on 2023-04-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SliderImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_1", models.ImageField(upload_to="Slider")),
                ("image_2", models.ImageField(upload_to="Slider")),
                ("image_3", models.ImageField(upload_to="Slider")),
            ],
        ),
    ]
