# Generated by Django 4.1.1 on 2023-05-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=255)),
                ("item_rate", models.CharField(max_length=255)),
                ("item_image", models.ImageField(upload_to="items")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_firstname", models.CharField(max_length=255)),
                ("user_lastname", models.CharField(max_length=255)),
                ("user_name", models.CharField(max_length=255)),
                ("user_dob", models.DateField()),
                ("user_gender", models.CharField(max_length=255)),
                ("user_phone", models.BigIntegerField()),
                ("alt_phone", models.BigIntegerField()),
                ("user_pin", models.CharField(max_length=255)),
                ("user_place", models.CharField(max_length=255)),
                ("user_country", models.CharField(max_length=255)),
                ("user_email", models.CharField(max_length=255)),
                ("user_address", models.CharField(max_length=255)),
            ],
        ),
    ]
