# Generated by Django 4.1.1 on 2023-04-26 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Stores", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SliderImage",
        ),
    ]
